name: Experimental

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Experimental action setup step
        uses: ./
        with:
          username: "eamonnk418"